from __future__ import annotations

from typing import Any


def hook_payload(name: str, *, command: str = "pwd") -> dict[str, Any]:
    payloads: dict[str, dict[str, Any]] = {
        "permission_request": {
            "cwd": "/path/to/project",
            "hook_event_name": "PermissionRequest",
            "model": "gpt-5",
            "permission_mode": "default",
            "session_id": "session-id",
            "tool_input": {"cmd": command},
            "tool_name": "shell",
            "transcript_path": None,
            "turn_id": "turn-id",
        },
        "post_compact": {
            "cwd": "/path/to/project",
            "hook_event_name": "PostCompact",
            "model": "gpt-5",
            "session_id": "session-id",
            "transcript_path": None,
            "trigger": "manual",
            "turn_id": "turn-id",
        },
        "post_tool_use": {
            "cwd": "/path/to/project",
            "hook_event_name": "PostToolUse",
            "model": "gpt-5",
            "permission_mode": "default",
            "session_id": "session-id",
            "tool_input": {"cmd": command},
            "tool_name": "shell",
            "tool_response": {"exit_code": 0, "stdout": "/path/to/project\n"},
            "tool_use_id": "tool-use-id",
            "transcript_path": None,
            "turn_id": "turn-id",
        },
        "pre_compact": {
            "cwd": "/path/to/project",
            "hook_event_name": "PreCompact",
            "model": "gpt-5",
            "session_id": "session-id",
            "transcript_path": None,
            "trigger": "manual",
            "turn_id": "turn-id",
        },
        "pre_tool_use": {
            "cwd": "/path/to/project",
            "hook_event_name": "PreToolUse",
            "model": "gpt-5",
            "permission_mode": "default",
            "session_id": "session-id",
            "tool_input": {"cmd": command},
            "tool_name": "shell",
            "tool_use_id": "tool-use-id",
            "transcript_path": None,
            "turn_id": "turn-id",
        },
        "session_start": {
            "cwd": "/path/to/project",
            "hook_event_name": "SessionStart",
            "model": "gpt-5",
            "permission_mode": "default",
            "session_id": "session-id",
            "source": "startup",
            "transcript_path": None,
        },
        "stop": {
            "cwd": "/path/to/project",
            "hook_event_name": "Stop",
            "last_assistant_message": "Done.",
            "model": "gpt-5",
            "permission_mode": "default",
            "session_id": "session-id",
            "stop_hook_active": False,
            "transcript_path": None,
            "turn_id": "turn-id",
        },
        "subagent_start": {
            "agent_id": "agent-id",
            "agent_type": "worker",
            "cwd": "/path/to/project",
            "hook_event_name": "SubagentStart",
            "model": "gpt-5",
            "permission_mode": "default",
            "session_id": "session-id",
            "transcript_path": None,
            "turn_id": "turn-id",
        },
        "subagent_stop": {
            "agent_id": "agent-id",
            "agent_transcript_path": None,
            "agent_type": "worker",
            "cwd": "/path/to/project",
            "hook_event_name": "SubagentStop",
            "last_assistant_message": "Done.",
            "model": "gpt-5",
            "permission_mode": "default",
            "session_id": "session-id",
            "stop_hook_active": False,
            "transcript_path": None,
            "turn_id": "turn-id",
        },
        "user_prompt_submit": {
            "cwd": "/path/to/project",
            "hook_event_name": "UserPromptSubmit",
            "model": "gpt-5",
            "permission_mode": "default",
            "prompt": "Please inspect the repository.",
            "session_id": "session-id",
            "transcript_path": None,
            "turn_id": "turn-id",
        },
    }
    return dict(payloads[name])


HOOK_SCHEMA_NAMES = {
    "permission_request": "permission-request",
    "post_compact": "post-compact",
    "post_tool_use": "post-tool-use",
    "pre_compact": "pre-compact",
    "pre_tool_use": "pre-tool-use",
    "session_start": "session-start",
    "stop": "stop",
    "subagent_start": "subagent-start",
    "subagent_stop": "subagent-stop",
    "user_prompt_submit": "user-prompt-submit",
}
