"""Structured Codex hook input models.

This file is generated by tools/generate_pydantic_models.py from the vendored
openai/codex hook input schemas. Do not edit it by hand.
"""

from __future__ import annotations

import json
import sys
from typing import Any, ClassVar, Literal, TextIO

from pydantic import BaseModel, ConfigDict, Field

from .schemas import validate


class StructuredInput(BaseModel):
    """Base class for schema-validated structured hook input."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    schema: ClassVar[str]

    def to_dict(self) -> dict[str, Any]:
        output = self.model_dump(by_alias=True, exclude_none=False, mode="json")
        validate(output, self.schema, direction="input")
        return output

    def validated(self) -> dict[str, Any]:
        return self.to_dict()

    @classmethod
    def from_dict(cls, data: dict[str, Any]):
        value = cls.model_validate(data)
        validate(value.to_dict(), cls.schema, direction="input")
        return value

    @classmethod
    def from_stream(cls, stream: TextIO = sys.stdin):
        data = json.load(stream)
        if not isinstance(data, dict):
            raise TypeError("hook payload must be a JSON object")
        return cls.from_dict(data)

    @classmethod
    def from_stdin(cls):
        return cls.from_stream(sys.stdin)


class PermissionRequestInput(StructuredInput):
    schema: ClassVar[str] = "permission-request"
    cwd: str = Field(default=..., alias='cwd')
    hook_event_name: Literal['PermissionRequest'] = Field(default=..., alias='hook_event_name')
    model: str = Field(default=..., alias='model')
    permission_mode: Literal['default', 'acceptEdits', 'plan', 'dontAsk', 'bypassPermissions'] = Field(default=..., alias='permission_mode')
    session_id: str = Field(default=..., alias='session_id')
    tool_input: Any = Field(default=..., alias='tool_input')
    tool_name: str = Field(default=..., alias='tool_name')
    transcript_path: str | None = Field(default=..., alias='transcript_path')
    turn_id: str = Field(default=..., alias='turn_id')

class PostCompactInput(StructuredInput):
    schema: ClassVar[str] = "post-compact"
    cwd: str = Field(default=..., alias='cwd')
    hook_event_name: Literal['PostCompact'] = Field(default=..., alias='hook_event_name')
    model: str = Field(default=..., alias='model')
    session_id: str = Field(default=..., alias='session_id')
    transcript_path: str | None = Field(default=..., alias='transcript_path')
    trigger: Literal['manual', 'auto'] = Field(default=..., alias='trigger')
    turn_id: str = Field(default=..., alias='turn_id')

class PostToolUseInput(StructuredInput):
    schema: ClassVar[str] = "post-tool-use"
    cwd: str = Field(default=..., alias='cwd')
    hook_event_name: Literal['PostToolUse'] = Field(default=..., alias='hook_event_name')
    model: str = Field(default=..., alias='model')
    permission_mode: Literal['default', 'acceptEdits', 'plan', 'dontAsk', 'bypassPermissions'] = Field(default=..., alias='permission_mode')
    session_id: str = Field(default=..., alias='session_id')
    tool_input: Any = Field(default=..., alias='tool_input')
    tool_name: str = Field(default=..., alias='tool_name')
    tool_response: Any = Field(default=..., alias='tool_response')
    tool_use_id: str = Field(default=..., alias='tool_use_id')
    transcript_path: str | None = Field(default=..., alias='transcript_path')
    turn_id: str = Field(default=..., alias='turn_id')

class PreCompactInput(StructuredInput):
    schema: ClassVar[str] = "pre-compact"
    cwd: str = Field(default=..., alias='cwd')
    hook_event_name: Literal['PreCompact'] = Field(default=..., alias='hook_event_name')
    model: str = Field(default=..., alias='model')
    session_id: str = Field(default=..., alias='session_id')
    transcript_path: str | None = Field(default=..., alias='transcript_path')
    trigger: Literal['manual', 'auto'] = Field(default=..., alias='trigger')
    turn_id: str = Field(default=..., alias='turn_id')

class PreToolUseInput(StructuredInput):
    schema: ClassVar[str] = "pre-tool-use"
    cwd: str = Field(default=..., alias='cwd')
    hook_event_name: Literal['PreToolUse'] = Field(default=..., alias='hook_event_name')
    model: str = Field(default=..., alias='model')
    permission_mode: Literal['default', 'acceptEdits', 'plan', 'dontAsk', 'bypassPermissions'] = Field(default=..., alias='permission_mode')
    session_id: str = Field(default=..., alias='session_id')
    tool_input: Any = Field(default=..., alias='tool_input')
    tool_name: str = Field(default=..., alias='tool_name')
    tool_use_id: str = Field(default=..., alias='tool_use_id')
    transcript_path: str | None = Field(default=..., alias='transcript_path')
    turn_id: str = Field(default=..., alias='turn_id')

class SessionStartInput(StructuredInput):
    schema: ClassVar[str] = "session-start"
    cwd: str = Field(default=..., alias='cwd')
    hook_event_name: Literal['SessionStart'] = Field(default=..., alias='hook_event_name')
    model: str = Field(default=..., alias='model')
    permission_mode: Literal['default', 'acceptEdits', 'plan', 'dontAsk', 'bypassPermissions'] = Field(default=..., alias='permission_mode')
    session_id: str = Field(default=..., alias='session_id')
    source: Literal['startup', 'resume', 'clear', 'compact'] = Field(default=..., alias='source')
    transcript_path: str | None = Field(default=..., alias='transcript_path')

class StopInput(StructuredInput):
    schema: ClassVar[str] = "stop"
    cwd: str = Field(default=..., alias='cwd')
    hook_event_name: Literal['Stop'] = Field(default=..., alias='hook_event_name')
    last_assistant_message: str | None = Field(default=..., alias='last_assistant_message')
    model: str = Field(default=..., alias='model')
    permission_mode: Literal['default', 'acceptEdits', 'plan', 'dontAsk', 'bypassPermissions'] = Field(default=..., alias='permission_mode')
    session_id: str = Field(default=..., alias='session_id')
    stop_hook_active: bool = Field(default=..., alias='stop_hook_active')
    transcript_path: str | None = Field(default=..., alias='transcript_path')
    turn_id: str = Field(default=..., alias='turn_id')

class SubagentStartInput(StructuredInput):
    schema: ClassVar[str] = "subagent-start"
    agent_id: str = Field(default=..., alias='agent_id')
    agent_type: str = Field(default=..., alias='agent_type')
    cwd: str = Field(default=..., alias='cwd')
    hook_event_name: Literal['SubagentStart'] = Field(default=..., alias='hook_event_name')
    model: str = Field(default=..., alias='model')
    permission_mode: Literal['default', 'acceptEdits', 'plan', 'dontAsk', 'bypassPermissions'] = Field(default=..., alias='permission_mode')
    session_id: str = Field(default=..., alias='session_id')
    transcript_path: str | None = Field(default=..., alias='transcript_path')
    turn_id: str = Field(default=..., alias='turn_id')

class SubagentStopInput(StructuredInput):
    schema: ClassVar[str] = "subagent-stop"
    agent_id: str = Field(default=..., alias='agent_id')
    agent_transcript_path: str | None = Field(default=..., alias='agent_transcript_path')
    agent_type: str = Field(default=..., alias='agent_type')
    cwd: str = Field(default=..., alias='cwd')
    hook_event_name: Literal['SubagentStop'] = Field(default=..., alias='hook_event_name')
    last_assistant_message: str | None = Field(default=..., alias='last_assistant_message')
    model: str = Field(default=..., alias='model')
    permission_mode: Literal['default', 'acceptEdits', 'plan', 'dontAsk', 'bypassPermissions'] = Field(default=..., alias='permission_mode')
    session_id: str = Field(default=..., alias='session_id')
    stop_hook_active: bool = Field(default=..., alias='stop_hook_active')
    transcript_path: str | None = Field(default=..., alias='transcript_path')
    turn_id: str = Field(default=..., alias='turn_id')

class UserPromptSubmitInput(StructuredInput):
    schema: ClassVar[str] = "user-prompt-submit"
    cwd: str = Field(default=..., alias='cwd')
    hook_event_name: Literal['UserPromptSubmit'] = Field(default=..., alias='hook_event_name')
    model: str = Field(default=..., alias='model')
    permission_mode: Literal['default', 'acceptEdits', 'plan', 'dontAsk', 'bypassPermissions'] = Field(default=..., alias='permission_mode')
    prompt: str = Field(default=..., alias='prompt')
    session_id: str = Field(default=..., alias='session_id')
    transcript_path: str | None = Field(default=..., alias='transcript_path')
    turn_id: str = Field(default=..., alias='turn_id')

__all__ = [
    'StructuredInput',
    'PermissionRequestInput',
    'PostCompactInput',
    'PostToolUseInput',
    'PreCompactInput',
    'PreToolUseInput',
    'SessionStartInput',
    'StopInput',
    'SubagentStartInput',
    'SubagentStopInput',
    'UserPromptSubmitInput',
]
