"""Structured Codex hook output models.

This file is generated by tools/generate_pydantic_outputs.py from the vendored
openai/codex hook output schemas. Do not edit it by hand.
"""

from __future__ import annotations

import json
import sys
from typing import Any, ClassVar, Literal, TextIO

from pydantic import BaseModel, ConfigDict, Field

from .schemas import validate


class StructuredOutput(BaseModel):
    """Base class for schema-validated structured hook output."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    schema: ClassVar[str]

    def to_dict(self) -> dict[str, Any]:
        output = self.model_dump(by_alias=True, exclude_none=True, mode="json")
        validate(output, self.schema, direction="output")
        return output

    def validated(self) -> dict[str, Any]:
        return self.to_dict()

    def write(self, stream: TextIO = sys.stdout) -> None:
        json.dump(self.to_dict(), stream, separators=(",", ":"))
        stream.write("\n")


class PermissionRequestDecision(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    behavior: Literal['allow', 'deny'] = Field(default=..., alias='behavior')
    interrupt: bool | None = Field(default=False, alias='interrupt')
    message: str | None = Field(default=None, alias='message')
    updated_input: Any | None = Field(default=None, alias='updatedInput')
    updated_permissions: Any | None = Field(default=None, alias='updatedPermissions')

class PermissionRequestHookSpecificOutput(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    decision: PermissionRequestDecision | None = Field(default=None, alias='decision')
    hook_event_name: Literal['PreToolUse', 'PermissionRequest', 'PostToolUse', 'PreCompact', 'PostCompact', 'SessionStart', 'UserPromptSubmit', 'SubagentStart', 'SubagentStop', 'Stop'] = Field(default=..., alias='hookEventName')

class PermissionRequestOutput(StructuredOutput):
    schema: ClassVar[str] = "permission-request"
    continue_: bool | None = Field(default=True, alias='continue')
    hook_specific_output: PermissionRequestHookSpecificOutput | None = Field(default=None, alias='hookSpecificOutput')
    stop_reason: str | None = Field(default=None, alias='stopReason')
    suppress_output: bool | None = Field(default=False, alias='suppressOutput')
    system_message: str | None = Field(default=None, alias='systemMessage')

    @classmethod
    def allow(cls, message: str | None = None) -> 'PermissionRequestOutput':
        return cls(
            hook_specific_output=PermissionRequestHookSpecificOutput(
                hook_event_name="PermissionRequest",
                decision=PermissionRequestDecision(behavior="allow", message=message),
            )
        )

    @classmethod
    def deny(cls, message: str) -> 'PermissionRequestOutput':
        return cls(
            hook_specific_output=PermissionRequestHookSpecificOutput(
                hook_event_name="PermissionRequest",
                decision=PermissionRequestDecision(behavior="deny", message=message),
            )
        )

class PostCompactOutput(StructuredOutput):
    schema: ClassVar[str] = "post-compact"
    continue_: bool | None = Field(default=True, alias='continue')
    stop_reason: str | None = Field(default=None, alias='stopReason')
    suppress_output: bool | None = Field(default=False, alias='suppressOutput')
    system_message: str | None = Field(default=None, alias='systemMessage')

    @classmethod
    def minimal(cls) -> 'PostCompactOutput':
        return cls(continue_=True)

class PostToolUseHookSpecificOutput(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    additional_context: str | None = Field(default=None, alias='additionalContext')
    hook_event_name: Literal['PreToolUse', 'PermissionRequest', 'PostToolUse', 'PreCompact', 'PostCompact', 'SessionStart', 'UserPromptSubmit', 'SubagentStart', 'SubagentStop', 'Stop'] = Field(default=..., alias='hookEventName')
    updated_mcp_tool_output: Any | None = Field(default=None, alias='updatedMCPToolOutput')

class PostToolUseOutput(StructuredOutput):
    schema: ClassVar[str] = "post-tool-use"
    continue_: bool | None = Field(default=True, alias='continue')
    decision: Literal['block'] | None = Field(default=None, alias='decision')
    hook_specific_output: PostToolUseHookSpecificOutput | None = Field(default=None, alias='hookSpecificOutput')
    reason: str | None = Field(default=None, alias='reason')
    stop_reason: str | None = Field(default=None, alias='stopReason')
    suppress_output: bool | None = Field(default=False, alias='suppressOutput')
    system_message: str | None = Field(default=None, alias='systemMessage')

    @classmethod
    def minimal(cls) -> 'PostToolUseOutput':
        return cls(hook_specific_output=PostToolUseHookSpecificOutput(hook_event_name="PostToolUse"))

class PreCompactOutput(StructuredOutput):
    schema: ClassVar[str] = "pre-compact"
    continue_: bool | None = Field(default=True, alias='continue')
    stop_reason: str | None = Field(default=None, alias='stopReason')
    suppress_output: bool | None = Field(default=False, alias='suppressOutput')
    system_message: str | None = Field(default=None, alias='systemMessage')

    @classmethod
    def minimal(cls) -> 'PreCompactOutput':
        return cls(continue_=True)

class PreToolUseHookSpecificOutput(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    additional_context: str | None = Field(default=None, alias='additionalContext')
    hook_event_name: Literal['PreToolUse', 'PermissionRequest', 'PostToolUse', 'PreCompact', 'PostCompact', 'SessionStart', 'UserPromptSubmit', 'SubagentStart', 'SubagentStop', 'Stop'] = Field(default=..., alias='hookEventName')
    permission_decision: Literal['allow', 'deny', 'ask'] | None = Field(default=None, alias='permissionDecision')
    permission_decision_reason: str | None = Field(default=None, alias='permissionDecisionReason')
    updated_input: Any | None = Field(default=None, alias='updatedInput')

class PreToolUseOutput(StructuredOutput):
    schema: ClassVar[str] = "pre-tool-use"
    continue_: bool | None = Field(default=True, alias='continue')
    decision: Literal['approve', 'block'] | None = Field(default=None, alias='decision')
    hook_specific_output: PreToolUseHookSpecificOutput | None = Field(default=None, alias='hookSpecificOutput')
    reason: str | None = Field(default=None, alias='reason')
    stop_reason: str | None = Field(default=None, alias='stopReason')
    suppress_output: bool | None = Field(default=False, alias='suppressOutput')
    system_message: str | None = Field(default=None, alias='systemMessage')

    @classmethod
    def allow(cls, additional_context: str | None = None) -> 'PreToolUseOutput':
        return cls(
            hook_specific_output=PreToolUseHookSpecificOutput(
                hook_event_name="PreToolUse",
                permission_decision="allow",
                additional_context=additional_context,
            )
        )

    @classmethod
    def deny(cls, reason: str) -> 'PreToolUseOutput':
        return cls(
            hook_specific_output=PreToolUseHookSpecificOutput(
                hook_event_name="PreToolUse",
                permission_decision="deny",
                permission_decision_reason=reason,
            )
        )

class SessionStartHookSpecificOutput(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    additional_context: str | None = Field(default=None, alias='additionalContext')
    hook_event_name: Literal['PreToolUse', 'PermissionRequest', 'PostToolUse', 'PreCompact', 'PostCompact', 'SessionStart', 'UserPromptSubmit', 'SubagentStart', 'SubagentStop', 'Stop'] = Field(default=..., alias='hookEventName')

class SessionStartOutput(StructuredOutput):
    schema: ClassVar[str] = "session-start"
    continue_: bool | None = Field(default=True, alias='continue')
    hook_specific_output: SessionStartHookSpecificOutput | None = Field(default=None, alias='hookSpecificOutput')
    stop_reason: str | None = Field(default=None, alias='stopReason')
    suppress_output: bool | None = Field(default=False, alias='suppressOutput')
    system_message: str | None = Field(default=None, alias='systemMessage')

    @classmethod
    def minimal(cls, additional_context: str | None = None) -> 'SessionStartOutput':
        return cls(hook_specific_output=SessionStartHookSpecificOutput(hook_event_name="SessionStart", additional_context=additional_context))

class StopOutput(StructuredOutput):
    schema: ClassVar[str] = "stop"
    continue_: bool | None = Field(default=True, alias='continue')
    decision: Literal['block'] | None = Field(default=None, alias='decision')
    reason: str | None = Field(default=None, alias='reason')
    stop_reason: str | None = Field(default=None, alias='stopReason')
    suppress_output: bool | None = Field(default=False, alias='suppressOutput')
    system_message: str | None = Field(default=None, alias='systemMessage')

    @classmethod
    def minimal(cls) -> 'StopOutput':
        return cls(continue_=True)

class SubagentStartHookSpecificOutput(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    additional_context: str | None = Field(default=None, alias='additionalContext')
    hook_event_name: Literal['PreToolUse', 'PermissionRequest', 'PostToolUse', 'PreCompact', 'PostCompact', 'SessionStart', 'UserPromptSubmit', 'SubagentStart', 'SubagentStop', 'Stop'] = Field(default=..., alias='hookEventName')

class SubagentStartOutput(StructuredOutput):
    schema: ClassVar[str] = "subagent-start"
    continue_: bool | None = Field(default=True, alias='continue')
    hook_specific_output: SubagentStartHookSpecificOutput | None = Field(default=None, alias='hookSpecificOutput')
    stop_reason: str | None = Field(default=None, alias='stopReason')
    suppress_output: bool | None = Field(default=False, alias='suppressOutput')
    system_message: str | None = Field(default=None, alias='systemMessage')

    @classmethod
    def minimal(cls, additional_context: str | None = None) -> 'SubagentStartOutput':
        return cls(hook_specific_output=SubagentStartHookSpecificOutput(hook_event_name="SubagentStart", additional_context=additional_context))

class SubagentStopOutput(StructuredOutput):
    schema: ClassVar[str] = "subagent-stop"
    continue_: bool | None = Field(default=True, alias='continue')
    decision: Literal['block'] | None = Field(default=None, alias='decision')
    reason: str | None = Field(default=None, alias='reason')
    stop_reason: str | None = Field(default=None, alias='stopReason')
    suppress_output: bool | None = Field(default=False, alias='suppressOutput')
    system_message: str | None = Field(default=None, alias='systemMessage')

    @classmethod
    def minimal(cls) -> 'SubagentStopOutput':
        return cls(continue_=True)

class UserPromptSubmitHookSpecificOutput(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    additional_context: str | None = Field(default=None, alias='additionalContext')
    hook_event_name: Literal['PreToolUse', 'PermissionRequest', 'PostToolUse', 'PreCompact', 'PostCompact', 'SessionStart', 'UserPromptSubmit', 'SubagentStart', 'SubagentStop', 'Stop'] = Field(default=..., alias='hookEventName')

class UserPromptSubmitOutput(StructuredOutput):
    schema: ClassVar[str] = "user-prompt-submit"
    continue_: bool | None = Field(default=True, alias='continue')
    decision: Literal['block'] | None = Field(default=None, alias='decision')
    hook_specific_output: UserPromptSubmitHookSpecificOutput | None = Field(default=None, alias='hookSpecificOutput')
    reason: str | None = Field(default=None, alias='reason')
    stop_reason: str | None = Field(default=None, alias='stopReason')
    suppress_output: bool | None = Field(default=False, alias='suppressOutput')
    system_message: str | None = Field(default=None, alias='systemMessage')

    @classmethod
    def minimal(cls, additional_context: str | None = None) -> 'UserPromptSubmitOutput':
        return cls(hook_specific_output=UserPromptSubmitHookSpecificOutput(hook_event_name="UserPromptSubmit", additional_context=additional_context))

__all__ = [
    'StructuredOutput',
    'PermissionRequestOutput',
    'PermissionRequestHookSpecificOutput',
    'PermissionRequestDecision',
    'PostCompactOutput',
    'PostToolUseOutput',
    'PostToolUseHookSpecificOutput',
    'PreCompactOutput',
    'PreToolUseOutput',
    'PreToolUseHookSpecificOutput',
    'SessionStartOutput',
    'SessionStartHookSpecificOutput',
    'StopOutput',
    'SubagentStartOutput',
    'SubagentStartHookSpecificOutput',
    'SubagentStopOutput',
    'UserPromptSubmitOutput',
    'UserPromptSubmitHookSpecificOutput',
]
