#!/usr/bin/env python3
"""Generate Pydantic input and output models from vendored Codex hook schemas."""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

SCHEMA_DIR = Path("third_party/openai-codex-hook-schemas/generated")
INPUT_DEST = Path("src/codex_hookkit/inputs.py")
OUTPUT_DEST = Path("src/codex_hookkit/outputs.py")

EVENT_NAMES = {
    "permission-request": "PermissionRequest",
    "post-compact": "PostCompact",
    "post-tool-use": "PostToolUse",
    "pre-compact": "PreCompact",
    "pre-tool-use": "PreToolUse",
    "session-start": "SessionStart",
    "stop": "Stop",
    "subagent-start": "SubagentStart",
    "subagent-stop": "SubagentStop",
    "user-prompt-submit": "UserPromptSubmit",
}

PY_RESERVED = {"continue": "continue_"}


def main() -> int:
    schema_names = sorted(EVENT_NAMES)
    INPUT_DEST.write_text(render_module(schema_names, direction="input"), encoding="utf-8")
    OUTPUT_DEST.write_text(render_module(schema_names, direction="output"), encoding="utf-8")
    print(f"generated {INPUT_DEST} and {OUTPUT_DEST} from {len(schema_names)} hook schemas")
    return 0


def render_module(schema_names: list[str], *, direction: str) -> str:
    chunks = [module_header(direction)]
    rendered_classes: set[str] = set()
    for schema_name in schema_names:
        chunks.append(
            render_schema(schema_name, direction=direction, rendered_classes=rendered_classes)
        )
    chunks.append(render_all(schema_names, direction=direction))
    return "\n\n".join(chunks).rstrip() + "\n"


def module_header(direction: str) -> str:
    title = "input" if direction == "input" else "output"
    base_class = base_class_name(direction)
    exclude_none = "False" if direction == "input" else "True"
    stream_methods = ""
    write_method = ""
    if direction == "input":
        stream_methods = """
    @classmethod
    def from_dict(cls, data: dict[str, Any]):
        value = cls.model_validate(data)
        validate(value.to_dict(), cls.schema, direction="input")
        return value

    @classmethod
    def from_stream(cls, stream: TextIO = sys.stdin):
        data = json.load(stream)
        if not isinstance(data, dict):
            raise TypeError("hook payload must be a JSON object")
        return cls.from_dict(data)

    @classmethod
    def from_stdin(cls):
        return cls.from_stream(sys.stdin)
"""
    else:
        write_method = """
    def write(self, stream: TextIO = sys.stdout) -> None:
        json.dump(self.to_dict(), stream, separators=(",", ":"))
        stream.write("\\n")
"""
    return f'''"""Structured Codex hook {title} models.

This file is generated by tools/generate_pydantic_models.py from the vendored
openai/codex hook {title} schemas. Do not edit it by hand.
"""

from __future__ import annotations

import json
import sys
from typing import Any, ClassVar, Literal, TextIO

from pydantic import BaseModel, ConfigDict, Field

from .schemas import validate


class {base_class}(BaseModel):
    """Base class for schema-validated structured hook {title}."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    schema: ClassVar[str]

    def to_dict(self) -> dict[str, Any]:
        output = self.model_dump(by_alias=True, exclude_none={exclude_none}, mode="json")
        validate(output, self.schema, direction="{direction}")
        return output

    def validated(self) -> dict[str, Any]:
        return self.to_dict()
{stream_methods}{write_method}'''


def render_schema(schema_name: str, *, direction: str, rendered_classes: set[str]) -> str:
    schema = load_schema(schema_name, direction=direction)
    event_name = EVENT_NAMES[schema_name]
    class_name = root_class_name(schema_name, direction=direction)
    definitions = schema.get("definitions", {})
    pieces: list[str] = []

    hook_ref = find_ref(schema, "hookSpecificOutput")
    hook_class = ""
    if hook_ref:
        hook_class = f"{event_name}HookSpecificOutput"
        for object_ref in object_refs(definitions[hook_ref], definitions):
            object_class_name = strip_wire(object_ref)
            if object_class_name not in rendered_classes:
                pieces.append(
                    render_object_definition(
                        definitions[object_ref], object_class_name, definitions
                    )
                )
                rendered_classes.add(object_class_name)
        pieces.append(render_object_definition(definitions[hook_ref], hook_class, definitions))
        rendered_classes.add(hook_class)

    pieces.append(
        render_root_class(
            schema_name,
            schema,
            direction=direction,
            class_name=class_name,
            hook_ref=hook_ref,
            hook_class=hook_class,
            definitions=definitions,
        )
    )
    return "\n\n".join(pieces)


def object_refs(definition: dict[str, Any], definitions: dict[str, Any]) -> list[str]:
    refs: list[str] = []
    for prop_schema in definition.get("properties", {}).values():
        ref = ref_name(prop_schema)
        if ref and definitions.get(ref, {}).get("type") == "object":
            refs.append(ref)
    return refs


def load_schema(schema_name: str, *, direction: str) -> dict[str, Any]:
    path = SCHEMA_DIR / f"{schema_name}.command.{direction}.schema.json"
    return json.loads(path.read_text(encoding="utf-8"))


def render_object_definition(
    definition: dict[str, Any],
    class_name: str,
    definitions: dict[str, Any],
) -> str:
    lines = [
        f"class {class_name}(BaseModel):",
        '    model_config = ConfigDict(extra="forbid", populate_by_name=True)',
    ]
    required = set(definition.get("required", []))
    for prop, prop_schema in definition.get("properties", {}).items():
        lines.append(render_field(prop, prop_schema, definitions, required=prop in required))
    if len(lines) == 2:
        lines.append("    pass")
    return "\n".join(lines)


def render_root_class(
    schema_name: str,
    schema: dict[str, Any],
    *,
    direction: str,
    class_name: str,
    hook_ref: str,
    hook_class: str,
    definitions: dict[str, Any],
) -> str:
    lines = [
        f"class {class_name}({base_class_name(direction)}):",
        f'    schema: ClassVar[str] = "{schema_name}"',
    ]
    required = set(schema.get("required", []))
    for prop, prop_schema in schema.get("properties", {}).items():
        if prop == "hookSpecificOutput" and hook_ref:
            prop_schema = {"allOf": [{"$ref": f"#/definitions/{hook_class}"}], "default": None}
        lines.append(
            render_field(
                prop,
                prop_schema,
                {**definitions, hook_class: {"type": "object"}},
                required=prop in required,
            )
        )
    if direction == "output":
        lines.append("")
        lines.extend(render_output_convenience_methods(schema_name, class_name, hook_class))
    return "\n".join(lines)


def render_output_convenience_methods(
    schema_name: str, class_name: str, hook_class: str
) -> list[str]:
    if schema_name == "pre-tool-use":
        return [
            "    @classmethod",
            f"    def allow(cls, additional_context: str | None = None) -> {class_name!r}:",
            "        return cls(",
            "            hook_specific_output=PreToolUseHookSpecificOutput(",
            '                hook_event_name="PreToolUse",',
            '                permission_decision="allow",',
            "                additional_context=additional_context,",
            "            )",
            "        )",
            "",
            "    @classmethod",
            f"    def deny(cls, reason: str) -> {class_name!r}:",
            "        return cls(",
            "            hook_specific_output=PreToolUseHookSpecificOutput(",
            '                hook_event_name="PreToolUse",',
            '                permission_decision="deny",',
            "                permission_decision_reason=reason,",
            "            )",
            "        )",
        ]
    if schema_name == "permission-request":
        return [
            "    @classmethod",
            f"    def allow(cls, message: str | None = None) -> {class_name!r}:",
            "        return cls(",
            "            hook_specific_output=PermissionRequestHookSpecificOutput(",
            '                hook_event_name="PermissionRequest",',
            (
                "                decision=PermissionRequestDecision("
                'behavior="allow", message=message),'
            ),
            "            )",
            "        )",
            "",
            "    @classmethod",
            f"    def deny(cls, message: str) -> {class_name!r}:",
            "        return cls(",
            "            hook_specific_output=PermissionRequestHookSpecificOutput(",
            '                hook_event_name="PermissionRequest",',
            (
                "                decision=PermissionRequestDecision("
                'behavior="deny", message=message),'
            ),
            "            )",
            "        )",
        ]
    if hook_class:
        event = EVENT_NAMES[schema_name]
        kwargs = [f'hook_event_name="{event}"']
        if schema_name in {"session-start", "subagent-start", "user-prompt-submit"}:
            signature = "additional_context: str | None = None"
            kwargs.append("additional_context=additional_context")
        else:
            signature = ""
        return [
            "    @classmethod",
            f"    def minimal(cls, {signature}) -> {class_name!r}:".replace("(cls, )", "(cls)"),
            f"        return cls(hook_specific_output={hook_class}({', '.join(kwargs)}))",
        ]
    return [
        "    @classmethod",
        f"    def minimal(cls) -> {class_name!r}:",
        "        return cls(continue_=True)",
    ]


def render_field(
    prop: str, prop_schema: dict[str, Any] | bool, definitions: dict[str, Any], *, required: bool
) -> str:
    py_name = PY_RESERVED.get(prop, camel_to_snake(prop))
    typ = type_expr(prop_schema, definitions, required=required)
    default = "..." if required else default_expr(prop_schema)
    field = f"Field(default={default}, alias={prop!r})"
    return f"    {py_name}: {typ} = {field}"


def type_expr(schema: dict[str, Any] | bool, definitions: dict[str, Any], *, required: bool) -> str:
    if schema is True:
        return maybe_optional("Any", required)
    if schema is False:
        return "Any"

    ref = ref_name(schema)
    if ref:
        if ref in definitions:
            definition = definitions[ref]
            if "enum" in definition:
                return maybe_optional(literal_type(definition["enum"]), required)
            if definition.get("type") == "object":
                return maybe_optional(strip_wire(ref), required)
            return maybe_optional(type_expr(definition, definitions, required=True), required)
        return maybe_optional(ref, required)
    if "const" in schema:
        return literal_type([schema["const"]])
    if "enum" in schema:
        return literal_type(schema["enum"])

    json_type = schema.get("type")
    if isinstance(json_type, list):
        non_null = [item for item in json_type if item != "null"]
        inner = json_type_expr(non_null[0] if non_null else "Any")
        nullable = "null" in json_type
        return maybe_optional(inner, required and not nullable)
    if isinstance(json_type, str):
        return maybe_optional(json_type_expr(json_type), required)
    return maybe_optional("Any", required)


def json_type_expr(json_type: str) -> str:
    if json_type == "string":
        return "str"
    if json_type == "boolean":
        return "bool"
    if json_type == "integer":
        return "int"
    if json_type == "number":
        return "float"
    if json_type == "array":
        return "list[Any]"
    if json_type == "object":
        return "dict[str, Any]"
    return "Any"


def maybe_optional(type_name: str, required: bool) -> str:
    return type_name if required else f"{type_name} | None"


def default_expr(schema: dict[str, Any] | bool) -> str:
    if not isinstance(schema, dict):
        return "None"
    default = schema.get("default", None)
    if default is True:
        return "True"
    if default is False:
        return "False"
    if isinstance(default, str):
        return repr(default)
    return "None"


def ref_name(schema: dict[str, Any] | bool) -> str:
    if not isinstance(schema, dict):
        return ""
    if "$ref" in schema:
        return schema["$ref"].split("/")[-1]
    for item in schema.get("allOf", []):
        if "$ref" in item:
            return item["$ref"].split("/")[-1]
    return ""


def find_ref(schema: dict[str, Any], prop: str) -> str:
    prop_schema = schema.get("properties", {}).get(prop, {})
    return ref_name(prop_schema)


def strip_wire(name: str) -> str:
    return name.removesuffix("Wire")


def literal_type(values: list[Any]) -> str:
    return "Literal[" + ", ".join(repr(value) for value in values) + "]"


def camel_to_snake(value: str) -> str:
    value = re.sub("(.)([A-Z][a-z]+)", r"\1_\2", value)
    value = re.sub("([a-z0-9])([A-Z])", r"\1_\2", value)
    return value.lower()


def root_class_name(schema_name: str, *, direction: str) -> str:
    suffix = "Input" if direction == "input" else "Output"
    return f"{EVENT_NAMES[schema_name]}{suffix}"


def base_class_name(direction: str) -> str:
    return "StructuredInput" if direction == "input" else "StructuredOutput"


def render_all(schema_names: list[str], *, direction: str) -> str:
    names = [base_class_name(direction)]
    for schema_name in sorted(schema_names):
        event = EVENT_NAMES[schema_name]
        names.append(root_class_name(schema_name, direction=direction))
        if direction == "output":
            if schema_name in {"pre-tool-use", "permission-request"}:
                names.append(f"{event}HookSpecificOutput")
                if schema_name == "permission-request":
                    names.append("PermissionRequestDecision")
            elif schema_name in {
                "post-tool-use",
                "session-start",
                "subagent-start",
                "user-prompt-submit",
            }:
                names.append(f"{event}HookSpecificOutput")
    joined = ",\n    ".join(repr(name) for name in names)
    return f"__all__ = [\n    {joined},\n]"


if __name__ == "__main__":
    raise SystemExit(main())
